### ISSUE TITLE
No need to apply font-weight:bold to h1, h2, or h3

### ISSUE THREAD

**Issue by jzhu01** [gauravmunjal84/prj-rev-bwfs-dasmoto#2]
Seen here: https://github.com/gauravmunjal84/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/index.css#L19-L21

Since the h1, h2, and h3 are all already bolded by default, adding this line doesn't affect the display.

**Comment by gauravmunjal84** [comment]
Thanks Zhu, making the change, learnt these headings are bold by default
